" Vim-Plug
call plug#begin('~/.vim/plugged')
Plug 'Valloric/YouCompleteMe', {
  \'do': './install.py --clang-completer --rust-completer --go-completer --java-completer',
  \'for': ['c', 'cpp', 'python', 'rust', 'go', 'java'],
  \}
Plug 'w0rp/ale'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'Reewr/vim-monokai-phoenix'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'rust-lang/rust.vim'
Plug 'solarnz/thrift.vim'
call plug#end()

set nocompatible

filetype on
filetype plugin on
filetype indent on
syntax on

set number

" Leader
let mapleader = ' '
let maplocalleader = ' '

" Language
let $LANG = 'en'
set langmenu=en
set encoding=utf-8

set backspace=indent,eol,start

" Search
set ignorecase
set smartcase
set hlsearch
set incsearch
set gdefault
set magic
nnoremap / :set hlsearch<cr>/\v
vnoremap / :set hlsearch<cr>/\v
nnoremap <silent><leader><space> :set nohlsearch<cr>

" Indent
set tabstop=2
set softtabstop=2
set shiftwidth=2
set shiftround
set autoindent
set smartindent
set expandtab
set smarttab

" Mark
noremap ' `
noremap ` '

" Accelerate
set ttyfast
set lazyredraw

" C-mode completion
set wildmenu
set wildmode=list:longest
set wildignore=*/.git,*/.hg,*/.svn

" Fold
set foldenable
set foldcolumn=2
set foldmethod=marker

" Split
set splitbelow
set splitright

" Color scheme
set background=dark
colorscheme monokai-phoenix

" Move cursor
noremap <expr> j v:count ? 'j' : 'gj'
noremap <expr> k v:count ? 'k' : 'gk'
noremap gj j
noremap gk k

" Buffer (act like vimium in chrome)
noremap <silent>J :bprev<cr>
noremap <silent>K :bnext<cr>

" Force save
command W w !sudo tee % > /dev/null

" YouCompleteMe
let g:ycm_confirm_extra_conf = 0
let g:ycm_global_ycm_extra_conf = '~/.vim/ycm.py'
let g:ycm_semantic_triggers = {
\ 'c,cpp,python,java,go,cs,javascript': ['re!\w{2}'],
\}
let g:ycm_error_symbol = 'E'
let g:ycm_warning_symbol = 'W'
let s:rust_sysroot = substitute(system('rustc --print sysroot'), '\n$', '', '')
let g:ycm_rust_src_path = s:rust_sysroot . '/lib/rustlib/src/rust/src'

" Asynchronous Lint Engine
let g:ale_linters = {
\ 'c': [],
\ 'cpp': [],
\ 'rust': ['cargo'],
\ 'python': ['flake8'],
\ 'vim': ['vint'],
\}
let g:ale_sign_warning = 'W'
let g:ale_sign_error = 'E'
let g:ale_lint_on_text_exchanged = 'always'
let g:ale_lint_on_insert_leave = 1
let g:ale_echo_msg_format = '[%linter%] %code: %%s'

" Airline
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline_symbols.crypt = '🔒'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.maxlinenr = ' '
let g:airline_symbols.branch = ''
let g:airline_symbols.paste = 'P'
let g:airline_symbols.whitespace = 'Ξ'
let g:airline_symbols.readonly = ''
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_theme = 'violet'

let g:airline#parts#ffenc#skip_expected_string = 'utf-8[unix]'
let g:airline#extensions#ale#enabled = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'

" Use terminal background color.
hi Normal ctermfg=NONE ctermbg=NONE
hi Pmenu ctermfg=NONE ctermbg=236 cterm=NONE
hi PmenuSel ctermfg=NONE ctermbg=24 cterm=NONE
