import Language.Haskell.HsColour
import Language.Haskell.HsColour.Colourise
let hlPrint = putStrLn . hscolour TTY defaultColourPrefs False False "" False . show

:set -interactive-print hlPrint
:set -XOverloadedStrings
:set -XScopedTypeVariables
:set -XPackageImports

:set +t
:set +s
:set +m

:set prompt "\n\ESC[1;34m%s\n\ESC[0;32mλ> \ESC[m"
:set prompt-cont "\ESC[0;32m | \ESC[m"

:module
