set-option -g escape-time 0
set-option -g mouse on
set-window-option -g mode-keys vi

# Switch between windows
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Resize windows
bind-key -r ^h resize-pane -L
bind-key -r ^j resize-pane -D
bind-key -r ^k resize-pane -U
bind-key -r ^l resize-pane -R

# Split window
bind-key - split-window -v -c '#{pane_current_path}'
bind-key \ split-window -h -c '#{pane_current_path}'
unbind-key '%'
unbind-key '"'
